### ISSUE TITLE
timeout for subdomain

### ISSUE THREAD

**Issue by random-robbie** [anshumanbh/tko-subs#10]
Can it ignore any issue like this?

```
root@76dd0dde8be2:/go/src/app# ./tko-subs -domains=domains.txt -data=providers-data.csv -output=output.csv
Get https://dl-origin.ubnt.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
panic: Get https://dl-origin.ubnt.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

goroutine 70 [running]:
main.scanforeachDomain(0xc4200c8bc0, 0x12, 0xc420094780, 0x14, 0x14, 0xc420015b60)
	/go/src/app/tko-subs.go:258 +0x976
created by main.main
	/go/src/app/tko-subs.go:423 +0x32a
root@76dd0dde8be2:/go/src/app# 

```

**Comment by anshumanbh** [comment]
would prolly need some code changes. I will take a look whenever I get some time.

**Comment by anshumanbh** [comment]
This should be fixed with the latest code push. If not, please create a new bug. Thanks!
